### PR TITLE
fix:Pick up airdrops according to the availability status of the airdrop distribution list

### PR DESCRIPTION
**Pull request by sigeshuo**
…rop distribution list

### CODE REVIEW

**Comment by yanpaing007** [comment]
I have never seen that api token/week,where did you find that and why did you put your ref code in there?
First airdrop claim is for first round and others for weekly

**Comment by sigeshuo** [comment]
> I have never seen that api token/week,where did you find that and why did you put your ref code in there? First airdrop claim is for first round and others for weekly

Accounts with a high rank can't see the per-round history list, you find an account with a low rank and you can see it.

**Comment by sigeshuo** [comment]
> I have never seen that api token/week,where did you find that and why did you put your ref code in there? First airdrop claim is for first round and others for weekly

Add the Ref ID so I can get in on some invite points as well. I set the weights lower.😊

**Comment by yanpaing007** [comment]
I saw that api in airdrop>history,thanks for your info,We need to check if user is qualify to claim toma for that round

**Pull request merged**
